site_name: disco-target
repo_url: https://github.com/loucerac/disco-target
site_url: https://loucerac.github.io/disco-target
site_description: Target dicovery for disease-driven drug repurposing.
site_author: Carlos Loucera
edit_uri: edit/main/docs/
repo_name: loucerac/disco-target
copyright: Maintained by <a href="https://loucerac.com">loucerac</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [disco_target]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/loucerac/disco-target
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/disco-target

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
